info:
  component: Api gateway Server
  
endpoints:
  restart:
    enabled: true
  shutdown:
    enabled: true
  health:
    sensitive: false

zuul:
  prefix: /api
  routes:
    contactservice: 
      path: /contacts/**
      serviceId: contact-service
    orderbook: 
      path: /order/**
      serviceId: order-service       
    referencedata: 
      path: /reference/**
      serviceId: referencedata-service
    salesbook: 
      path: /sales/**
      serviceId: sales-service
    search: 
      path:/search/**
      serviceId:search-service
    security: 
      path:/security/**
      serviceId:security-service
    storekeeper:
      path:/storekeeper/**
      serviceId:storekeeper-service
      
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 20000
      
eureka:
  client:
    serviceUrl:
     defaultZone: http://localhost:8761/eureka/
    registerWithEureka: false
      
server:
  port: 8765

logging:
  level:
    ROOT: INFO
    org.springframework.web: DEBUG